### PR TITLE
Added support for showing the date/time picker even when field isn't empty.

### PR DESCRIPTION
**Pull request by noordawod**

### CODE REVIEW

**Comment by noordawod** [comment]
@jifalops 
If you merge this in, I have another one waiting :)

**Comment by jifalops** [comment]
@noordawod Sorry just getting to this.

**Comment by jifalops** [comment]
Added in release v0.1.5

**Comment by jifalops** [comment]
This made me realize a design flaw in this widget and a similar one I have published. Since their state must extend `FormFieldState<T>` instead of `State<DateTimePickerFormField>`, the state's `widget` isn't the correct one containing the various options set on the widget. That's why I made `parent`, which refers to the state's actual `DateTimePickerFormField`. It turns out dynamically changing properties on the widget will not propagate properly to the state. 

In testing this PR, toggling the "editable" option (what I ended up renaming "showPickerAlways" to), had no effect on the widget. But that is actually part of the design and a flaw with most of the available options.

**Comment by noordawod** [comment]
So, `showPickerAlways` is now called `editable`, and its default value is `true`.

This means that the input will be editable and show the pickers, which is the opposite of the original PR. Just pointing it out for the benefit of others.

**Comment by jifalops** [comment]
The functionality should be the same as the PR, but instead of having `showPickerAlways` default to false, `editable` defaults to true, since the two names are semantic opposites. Is there a side effect I should be aware of or something else that changed?

**Comment by noordawod** [comment]
Ohh I don't think so, I was just pointing it out for others who may have used the previous parameter with `false` and now use the new parameter but didn't change to `true`.

**Pull request merged**
